### ISSUE TITLE
Validate/redesign vaccination status field

### ISSUE THREAD

**Issue by dannn-tran** [AY2021S2-CS2103T-W10-4/tp#234]
If `vaccinationStatus` field in the JSON file is edited to something other than `vaccinated` and `not vaccinated`, it will always be displayed as red. This can be misleading when `Vaccinated` appears red. #210, #207

Solution: Validate the `vaccinationStatus` value to accept these 2 values only. Can also consider changing the value to boolean in model and storage in JSON, but keep the command format the same.

**Comment by SiTingST** [comment]
How about we change the value of the vaccination status  to be "vaccinated" and "unvaccinated"?

**Comment by fairyinabottle4** [comment]
@picasdan9 @SiTingST I like the idea of using boolean values, since it is unambiguous and yet keep the command format intact.

In fact I think using 0 and 1 would be the best. This is to prevent ambiguity regarding the capitalization of the boolean values e.g. `true vs True`. We are already using enum for this, so it should be quite similar
